# Generated by Django 4.1.2 on 2022-10-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='Artiste',
            new_name='artiste_id',
        ),
        migrations.AlterField(
            model_name='lyric',
            name='content',
            field=models.TextField(),
        ),
    ]
